### ISSUE TITLE
Voir pourquoi il y a un bug / erreur 500 lors des commandes

### ISSUE THREAD

**Issue by yannbug** [Celyan-SAS/Marketplace-gateway-for-Dokan-and-MANGOPAY#1]
WP est en mode debug donc si l'erreur sort pas on cherchera dans les logs, mais en général c'est souvent des appels de classe manquantes.

**Comment by SilverCelyan** [comment]
quand on press "proceder a la commande" il y a un warning qui ressort 
"undefined index mp_payment_type" dans gateway.inc.php line 372 dans mangopay
Je sais que c'est pas ça qu'on recherche mais pour dire que c'est la

**Comment by yannbug** [comment]
Ok donc il faut enquêter là-dessus aussi. Si c'est un bug du côté du plugin MANGOPAY-WooCommerce on le remontera là-bas.
